### ISSUE TITLE
missing MSVCP140.dll…

### ISSUE THREAD

**Issue by wjbfarrell** [mhbeals/quotepdf#1]
Hi Melodee,

This is great, but some of my colleagues are getting an error message when they download the .exe file: 

> missing MSVCP140.dll…

Do you know if this a Windows issue? Can it be ignored?

William

**Comment by mhbeals** [comment]
Thanks!

It is and it isn't.  In order to run newly compiled Visual C++ programmes (such as QuotePDF) you need to have all the Windows10 updates.  If you are on Windows 7 or a bit behind in your (optional) updates you might need to install this one: 

https://www.microsoft.com/en-gb/download/details.aspx?id=48145 (Visual C++ Redistributable for Visual Studio 2015)

I have updated the Readme to include this information. Let me know if anything further crops up.

**Comment by wjbfarrell** [comment]
Ah, OK that makes sense. Thanks a lot.
